"""empty message

Revision ID: 33dfa957dfec
Revises: fc18d91210d5
Create Date: 2024-01-10 20:38:54.470928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dfa957dfec'
down_revision: Union[str, None] = 'fc18d91210d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE statusevent ADD VALUE 'cancelled'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
