"""empty message

Revision ID: 4ddb63c5e0bf
Revises: 133b76879e2f
Create Date: 2024-03-16 19:11:12.065613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddb63c5e0bf'
down_revision: Union[str, None] = '133b76879e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=25), nullable=False),
    sa.Column('text', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('pathfile', sa.String(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=40), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['news_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )


def downgrade() -> None:
    op.drop_table('news')
    op.drop_table('news_category')
