"""empty message

Revision ID: 834167e4504c
Revises: b4a8c3c9a7c2
Create Date: 2024-01-10 20:36:43.072672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834167e4504c'
down_revision: Union[str, None] = 'b4a8c3c9a7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade():
        op.execute("ALTER TYPE status_event ADD VALUE 'cancelled'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
