"""empty message

Revision ID: 95d9e045cd61
Revises: 7d054f8a4243
Create Date: 2024-03-10 02:29:52.847371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d9e045cd61'
down_revision: Union[str, None] = '7d054f8a4243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN tg_id TYPE INTEGER USING tg_id::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN tg_id TYPE VARCHAR USING tg_id::integer"')
