"""empty message

Revision ID: 9a4bb302ed95
Revises: a23c435dc66b
Create Date: 2024-01-23 17:12:19.973931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4bb302ed95'
down_revision: Union[str, None] = 'a23c435dc66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('slug', sa.VARCHAR(length=40), nullable=False))
    op.create_unique_constraint(None, 'team', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'slug')
    # ### end Alembic commands ###
