"""empty message

Revision ID: a8c14b5b51c0
Revises: eed53940ab7d
Create Date: 2024-01-06 18:38:13.589453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c14b5b51c0'
down_revision: Union[str, None] = 'eed53940ab7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('is_captain_only_search', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('rating_5x5', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating_5x5')
    op.drop_column('team', 'is_captain_only_search')
    # ### end Alembic commands ###
