"""empty message

Revision ID: b4a8c3c9a7c2
Revises: c6ace79a184e
Create Date: 2024-01-10 20:33:42.939894

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a8c3c9a7c2'
down_revision: Union[str, None] = 'c6ace79a184e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'status',
               existing_type=postgresql.ENUM('opened', 'pending', 'actived', 'finished',
                                             'cancelled', name='statusevent'),
               nullable=True)
    op.alter_column('match_5x5', 'status',
               existing_type=postgresql.ENUM('opened', 'pending', 'actived', 'finished',
                                             'cancelled', name='statusevent'),
               nullable=True)
    op.alter_column('solomatch', 'status',
               existing_type=postgresql.ENUM('opened', 'pending', 'actived', 'finished',
                                             'cancelled', name='statusevent'),
               nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
