"""empty message

Revision ID: bd99a267a62f
Revises: a9f2bcfa4320
Create Date: 2024-02-01 14:55:08.716955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd99a267a62f"
down_revision: Union[str, None] = "a9f2bcfa4320"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phone_number", sa.VARCHAR(length=12), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
