"""empty message

Revision ID: e0d82cdf4a25
Revises: 2d1c1967275c
Create Date: 2024-01-07 15:29:41.141563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d82cdf4a25'
down_revision: Union[str, None] = '2d1c1967275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
