"""empty message

Revision ID: eb7a493ef282
Revises: 0ef6134abf07
Create Date: 2023-12-18 21:56:14.833253

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7a493ef282'
down_revision: Union[str, None] = '0ef6134abf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_solomatch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fk', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('solomatch_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solomatch_fk'], ['solomatch.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_solomatch')
    # ### end Alembic commands ###
