"""empty message

Revision ID: fc18d91210d5
Revises: 834167e4504c
Create Date: 2024-01-10 20:37:36.824426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc18d91210d5'
down_revision: Union[str, None] = '834167e4504c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade() -> None:
        op.execute("ALTER TYPE statusevent ADD VALUE 'cancelled'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
