name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 176.109.110.111
          username: menoitami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd basketball-mm
            git pull
            docker-compose down
            docker-compose up -d
